Here we go! Given a filename in a string (like 'test.jpg'), return the file extension (like 'jpg'), OR false if it doesn't have one.
Testing "getFileExtension('blatherskite.png');"...
RIGHT: png is the right answer.
Testing "getFileExtension('perfectlylegal.torrent');"...
RIGHT: torrent is the right answer.
Testing "getFileExtension('spaces are fine in file names.txt');"...
RIGHT: txt is the right answer.
Testing "getFileExtension('this does not have one');"...
RIGHT: false is the right answer.
Testing "getFileExtension('.htaccess');"...
RIGHT: htaccess is the right answer.




Return the longest string inside it.
Testing "longestString(['a','ab','abc']);"...
RIGHT: abc is the right answer.
Testing "longestString(['big',[0,1,2,3,4],'tiny']);"...
RIGHT: tiny is the right answer.
Testing "longestString(['Hi','World','你好']);"...
RIGHT: World is the right answer.
Testing "longestString([true,false,'lol']);"...
RIGHT: lol is the right answer.
Testing "longestString([{object: true,mainly: 'to confuse you'},'x']);"...
RIGHT: x is the right answer.
SUCCESS! All tests passed. You've used 72:15 so far. Well done!
